use customer_behavior;

Select * from customer;

-- What is the total revenue generated by male and female customers?

Select gender , SUM(purchase_amount_usd) as Total_revenue 
from customer
group by gender;

-- Which customers used discount but still spend more than average purchase amount

Select customer_id ,purchase_amount_usd
from customer
where discount_applied = 'Yes' and
purchase_amount_usd >= 
(
Select Avg(purchase_amount_usd) as avg_purchase_amount  from customer 
);

-- What are the top 5 products with highest average review rating

Select Top 5 item_purchased, ROUND(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating DESC;

-- Compare the average Purchase amounts between Standard and Express Shipping

Select shipping_type, AVG(purchase_amount_usd) as avg_purchase_amount
from customer
where shipping_type IN ('Standard', 'Express')
group by shipping_type;

-- Do subscribed customers spend more ? Compare average spend and 
-- total revenue between subscribers and non-subscribers

Select subscription_status , 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount_usd),2) as average_spend,
ROUND(SUM(purchase_amount_usd),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend DESC;


-- Which 5 products have the highest percentage of purchase with discounts applied?

Select top 5 item_purchased , 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 Else 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC;

-- Segment customers into New, Returning, and Loyal based on their total number of 
-- previous purchases, and show the count of each segment. 

with customer_type as 
(
Select customer_id , previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

Select customer_segment , COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment;


-- What are the top 3 most purchase product with each category 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select  subscription_status, COUNT(customer_id) as repeat_buyers 
from customer
where previous_purchases > 5
GROUP BY subscription_status ;


-- What is the revenue contribution of each age group? 

SELECT age_group , 
    SUM(purchase_amount_usd) as total_revenue
from customer
group by age_group
ORDER BY total_revenue DESC;